# This is a template workflow 

name: Deploy Mule APIs to CloudHub

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the qa, main branch
  push:
    branches:
      - dev
    # Don't trigger the workflow when only workflow file / gitignore / README has the changes
    paths-ignore: 
      - '.gitignore'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Test & Build
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout this repo
        uses: actions/checkout@v3
 
      - name: GET Application Version
        run: |
          curl --location --request GET 'https://anypoint.mulesoft.com/exchange/api/v2/assets/bd7f4d4d-1fcc-4b30-94a5-4eafbebdf8ff/test' -u ~~~Client~~~:22587927742a4ce6bc156f3d9d1f6dfe~?~e77c4B0540994C7DBEcF6f6d94B663e3 -o response.json
          echo "EXCH_APP_VERSION=$(jq '.version' response.json)" >> $GITHUB_ENV 
      - name: Print Exchange app version
        run: echo $EXCH_APP_VERSION
     
      - name: check version with pom 
        run: echo '$(EXCH_APP_VERSION)\n1.2.2' | sort -V 
